<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Sim.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sim.Core\Sim.Core.csproj" />
    <ProjectReference Include="..\Sim.Protocol\Sim.Protocol.csproj" />
  </ItemGroup>

</Project>
