<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sim.Core\Sim.Core.csproj" />
    <ProjectReference Include="..\Sim.Mujoco\Sim.Mujoco.csproj" />
  </ItemGroup>
</Project>
